"use client";

import { useMemo, useState } from "react";
import { ALIASES, CONFESSIONS, SESSION_NOTICE, type Confession, type ConfessionCategory } from "@/lib/campus-data";
import { useSessionItems } from "@/lib/session-store";
import { DemoNotice } from "@/components/os/DemoNotice";
import { EmptyState } from "@/components/os/EmptyState";
import { PageIntro } from "@/components/os/PageIntro";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
const categories: Array<"All" | ConfessionCategory> = ["All", "Campus", "Academics", "Hostel", "Canteen", "Unsent", "Wholesome"];
export default function ConfessionsPage() { const { items, prepend, update } = useSessionItems<Confession>("campusos.confessions", CONFESSIONS); const [query, setQuery] = useState(""); const [category, setCategory] = useState<(typeof categories)[number]>("All"); const [body, setBody] = useState(""); const [message, setMessage] = useState(""); const list = useMemo(() => items.filter((c) => (category === "All" || c.category === category) && c.body.toLowerCase().includes(query.toLowerCase())), [items, category, query]); const respond = (id: string) => { const text = window.prompt("Reply anonymously (session only):"); if (!text?.trim()) return; update((all) => all.map((c) => c.id === id ? {...c, replies: [...c.replies, {id: crypto.randomUUID(), alias: "Quiet Bench", body: text.trim(), createdAt: new Date().toISOString()}]} : c)); };
return <div className="space-y-6"><PageIntro kicker="Community" title="Confessions" description="A deliberately anonymous board. No identity, email, or profile is shown in a confession." /><DemoNotice />
<section className="glass rounded-3xl p-5"><label htmlFor="confession" className="text-sm font-medium">Say it anonymously</label><Textarea id="confession" value={body} onChange={(e) => setBody(e.target.value)} placeholder="Keep it kind, specific, and safe…" className="mt-3 min-h-24"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><select aria-label="Confession category" className="h-9 rounded-lg border border-input bg-background px-2 text-sm" value={category === "All" ? "Campus" : category} onChange={(e) => setCategory(e.target.value as ConfessionCategory)}>{categories.slice(1).map((c) => <option key={c}>{c}</option>)}</select><Button className="rounded-full" onClick={() => { if (!body.trim()) return; prepend({id: crypto.randomUUID(), alias: ALIASES[Math.floor(Math.random()*ALIASES.length)], category: category === "All" ? "Campus" : category, body: body.trim(), createdAt: new Date().toISOString(), reactions: {relate: 0, hug: 0, wild: 0}, replies: [], sessionLocal: true}); setBody(""); setMessage("Posted anonymously in this browser session only."); }}>Post anonymously</Button></div><p className="mt-2 text-[11px] text-muted-foreground">{message || SESSION_NOTICE}</p></section>
<div className="flex flex-col gap-3 sm:flex-row"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search confession text" className="sm:max-w-xs"/><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((c) => <Button key={c} size="sm" variant={category === c ? "default" : "outline"} className="shrink-0 rounded-full" onClick={() => setCategory(c)}>{c}</Button>)}</div></div>
{list.length === 0 ? <EmptyState title="The board is quiet" body="Try another category or share an anonymous thought."/> : <div className="space-y-4">{list.map((c) => <article key={c.id} className="rounded-3xl border border-border p-5"><div className="flex justify-between"><div><p className="font-medium">{c.alias}</p><p className="text-xs text-muted-foreground">Anonymous · {c.category}{c.sessionLocal ? " · this session" : " · demo"}</p></div><Button variant="ghost" size="sm" onClick={() => setMessage("Report affordance recorded locally; no moderation team has been contacted.")}>Report</Button></div><p className="mt-3 text-sm leading-relaxed">{c.body}</p><div className="mt-4 flex flex-wrap gap-2">{(["relate","hug","wild"] as const).map((r) => <Button key={r} variant="outline" size="sm" onClick={() => update((all) => all.map((x) => x.id === c.id ? {...x, reactions: {...x.reactions, [r]: x.reactions[r] + 1}} : x))}>{r} {c.reactions[r]}</Button>)}<Button variant="ghost" size="sm" onClick={() => respond(c.id)}>Reply ({c.replies.length})</Button></div>{c.replies.map((r) => <p key={r.id} className="mt-3 border-l border-border pl-3 text-sm"><span className="font-medium">{r.alias}: </span>{r.body}</p>)}</article>)}</div>}</div>; }
