"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { useNotifications } from "@/lib/notifications";
import { SessionStorageNotice } from "@/components/os/SessionStorageNotice";
import { PageIntro } from "@/components/os/PageIntro";
import { DemoNotice } from "@/components/os/DemoNotice";
import { EmptyState } from "@/components/os/EmptyState";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export default function NotificationsPage() { const { items, markRead, markAllRead, storageError } = useNotifications(); const [query, setQuery] = useState(""); const list = useMemo(() => items.filter((n) => `${n.title} ${n.body}`.toLowerCase().includes(query.toLowerCase())), [items, query]); return <div data-controls className="space-y-6 stagger-in"><PageIntro kicker="System" title="Notifications" description="CampusOS alerts from this demo product. Read state is shared across CampusOS for this browser session."/><DemoNotice/><SessionStorageNotice message={storageError} /><div className="flex flex-col gap-3 sm:flex-row stagger-in"><Input aria-label="Search notifications" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search notifications" className="sm:max-w-xs"/><Button variant="outline" disabled={!items.some((item) => item.unread)} onClick={markAllRead}>Mark all read</Button></div>{list.length === 0 ? (query ? <EmptyState title="No notifications match" body="Try a different search."/> : <EmptyState title="Nothing demanding your attention." body="You're caught up. New campus alerts will land here."/>) : <div className="surface-list stagger-in">{list.map((n) => <article key={n.id} data-surface="row" data-unread={n.unread} data-surface-density="compact"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><p className="font-medium">{n.title}</p><p className="mt-1 text-body-sm text-muted-foreground">{n.body}</p><p className="mt-2 text-caption text-muted-foreground">{n.time} · {n.unread ? "Unread" : "Read"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" disabled={!n.unread} onClick={() => markRead(n.id)}>Mark read</Button><Link onClick={() => markRead(n.id)} href={n.href} data-control="button" data-size="sm">Open</Link></div></div></article>)}</div>}</div>; }
